### ISSUE TITLE
Why not use launch-agent?

### ISSUE THREAD

**Issue by tristan-k** [digitalcora/homebrew-notifier#1]
Why do you prefer crontab over launch-agent?

**Comment by grantovich** [comment]
Hi @tristan-k, no particular reason other than familiarity. It seems like a launch agent might be a more reliable way to deliver the notifications, and I would totally accept a pull request to that effect (as long as the setup script is still idempotent).

**Comment by digitalcora** [comment]
Closing this old issue, as I am archiving this project and no longer plan to maintain it.
